# Generated by Django 5.1.6 on 2025-02-24 16:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="alert",
            name="message",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="alert",
            name="timeStamp",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, null=True
            ),
        ),
        migrations.AlterField(
            model_name="alert",
            name="status",
            field=models.CharField(
                choices=[("UNKNOWN", "Unknown"), ("UP", "Up"), ("DOWN", "Down")],
                default="UNKNOWN",
                max_length=10,
            ),
        ),
    ]
