# Generated by Django 5.1.6 on 2025-02-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alert", "0002_alert_is_read_alert_message_alert_timestamp_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alert",
            name="url",
            field=models.URLField(null=True, unique=True),
        ),
    ]
