# Generated by Django 5.1.6 on 2025-03-06 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alert", "0004_alter_alert_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="timeStamp",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
