# Generated by Django 5.1.6 on 2025-03-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("alert", "0005_alter_alert_timestamp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="timeStamp",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
