version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  web:
    build: .
    container_name: django_web
    command: ["gunicorn", "-b", "0.0.0.0:8000", "process_monitoring.wsgi:application"]
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis

  celery:
    build: .
    container_name: celery_worker
    command: ["celery", "-A", "process_monitoring", "worker", "--loglevel=info"]
    depends_on:
      - redis
      - web

  celery-beat:
    build: .
    container_name: celery_beat
    command: ["celery", "-A", "process_monitoring", "beat", "--loglevel=info"]
    depends_on:
      - redis
      - web
