# Generated by Django 5.1.6 on 2025-03-06 10:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Website",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
                ("status", models.CharField(default="UNKNOWN", max_length=10)),
                (
                    "interval",
                    models.IntegerField(
                        choices=[
                            (30, "Every 30 sec"),
                            (60, "Every 1 min"),
                            (120, "Every 2 min"),
                            (300, "Every 5 min"),
                        ],
                        default=60,
                    ),
                ),
                ("last_checked", models.DateTimeField(auto_now=True)),
                ("monitoring_type", models.CharField(default="server", max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
