# Generated by Django 5.1.6 on 2025-03-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="interval",
            field=models.IntegerField(
                choices=[
                    (20, "Every 10 sec"),
                    (60, "Every 1 min"),
                    (120, "Every 2 min"),
                    (300, "Every 5 min"),
                ],
                default=60,
            ),
        ),
    ]
