# Generated by Django 5.1.6 on 2025-02-24 16:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0002_task_delete_alert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Task",
            new_name="Alert",
        ),
    ]
