# Generated by Django 5.1.6 on 2025-02-24 16:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("monitoring", "0003_rename_task_alert"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Alert",
            new_name="AlertStatus",
        ),
    ]
